name: goim.worker.msg
version: v0.0.0
log:
  level: DEBUG
http:
  scheme: http
  port: 18041
redis:
  addr: 127.0.0.1:6379
mq:
  addr:
    - 127.0.0.1:9876
# services name
gatewayService: service.goim.gateway
userService: service.goim.user
pushService: service.goim.push
storeService: service.goim.store
msgService: service.goim.msg